const ITEMS_DATA = [
    {id:1,name:'Potion',category:'medicine',subcategory:'heal',effect:'heal_20',effect_value:20,desc:'Cura 20 HP.',price:300,holdable:false,battle:true,sprite:'assets/sprites/items/potion.png'},
    {id:2,name:'Super Potion',category:'medicine',subcategory:'heal',effect:'heal_50',effect_value:50,desc:'Cura 50 HP.',price:700,holdable:false,battle:true,sprite:'assets/sprites/items/super-potion.png'},
    {id:3,name:'Hyper Potion',category:'medicine',subcategory:'heal',effect:'heal_200',effect_value:200,desc:'Cura 200 HP.',price:1200,holdable:false,battle:true,sprite:'assets/sprites/items/hyper-potion.png'},
    {id:4,name:'Max Potion',category:'medicine',subcategory:'heal',effect:'heal_full',effect_value:9999,desc:'Cura todo HP.',price:2500,holdable:false,battle:true,sprite:'assets/sprites/items/max-potion.png'},
    {id:5,name:'Full Restore',category:'medicine',subcategory:'heal',effect:'heal_full_status',effect_value:9999,desc:'Cura todo HP e status.',price:3000,holdable:false,battle:true,sprite:'assets/sprites/items/full-restore.png'},
    {id:10,name:'Poké Ball',category:'pokeball',subcategory:'standard',effect:'catch_1x',effect_value:1,desc:'Pokébola básica.',price:200,holdable:false,battle:true,sprite:'assets/sprites/items/poke-ball.png'},
    {id:11,name:'Great Ball',category:'pokeball',subcategory:'standard',effect:'catch_1.5x',effect_value:1.5,desc:'Maior chance.',price:600,holdable:false,battle:true,sprite:'assets/sprites/items/great-ball.png'},
    {id:12,name:'Ultra Ball',category:'pokeball',subcategory:'standard',effect:'catch_2x',effect_value:2,desc:'Alta chance.',price:1200,holdable:false,battle:true,sprite:'assets/sprites/items/ultra-ball.png'},
    {id:13,name:'Master Ball',category:'pokeball',subcategory:'master',effect:'catch_100x',effect_value:100,desc:'Captura sempre.',price:0,holdable:false,battle:true,sprite:'assets/sprites/items/master-ball.png'},
    {id:20,name:'Revive',category:'medicine',subcategory:'revive',effect:'revive_half',effect_value:0.5,desc:'Revive com metade HP.',price:1500,holdable:false,battle:false,sprite:'assets/sprites/items/revive.png'},
    {id:21,name:'Max Revive',category:'medicine',subcategory:'revive',effect:'revive_full',effect_value:1,desc:'Revive com HP total.',price:3000,holdable:false,battle:false,sprite:'assets/sprites/items/max-revive.png'},
    {id:30,name:'Antidote',category:'medicine',subcategory:'status',effect:'cure_poison',desc:'Cura envenenamento.',price:100,holdable:false,battle:true,sprite:'assets/sprites/items/antidote.png'},
    {id:31,name:'Paralyze Heal',category:'medicine',subcategory:'status',effect:'cure_paralyze',desc:'Cura paralisia.',price:200,holdable:false,battle:true,sprite:'assets/sprites/items/paralyze-heal.png'},
    {id:32,name:'Awakening',category:'medicine',subcategory:'status',effect:'cure_sleep',desc:'Acorda Pokémon.',price:200,holdable:false,battle:true,sprite:'assets/sprites/items/awakening.png'},
    {id:33,name:'Burn Heal',category:'medicine',subcategory:'status',effect:'cure_burn',desc:'Cura queimadura.',price:200,holdable:false,battle:true,sprite:'assets/sprites/items/burn-heal.png'},
    {id:34,name:'Ice Heal',category:'medicine',subcategory:'status',effect:'cure_freeze',desc:'Descongela.',price:200,holdable:false,battle:true,sprite:'assets/sprites/items/ice-heal.png'},
    {id:35,name:'Full Heal',category:'medicine',subcategory:'status',effect:'cure_all_status',desc:'Cura qualquer status.',price:400,holdable:false,battle:true,sprite:'assets/sprites/items/full-heal.png'},
    {id:40,name:'Rare Candy',category:'medicine',subcategory:'exp',effect:'level_up',effect_value:1,desc:'+1 nível.',price:10000,holdable:false,battle:false,sprite:'assets/sprites/items/rare-candy.png'},
    {id:50,name:'X Attack',category:'battle_item',subcategory:'stat',effect:'boost_attack',desc:'+1 ataque na batalha.',price:500,holdable:false,battle:true,sprite:'assets/sprites/items/x-attack.png'},
    {id:51,name:'X Defense',category:'battle_item',subcategory:'stat',effect:'boost_defense',desc:'+1 defesa na batalha.',price:550,holdable:false,battle:true,sprite:'assets/sprites/items/x-defense.png'},
    {id:52,name:'X Speed',category:'battle_item',subcategory:'stat',effect:'boost_speed',desc:'+1 velocidade.',price:350,holdable:false,battle:true,sprite:'assets/sprites/items/x-speed.png'},
    {id:53,name:'X Sp. Atk',category:'battle_item',subcategory:'stat',effect:'boost_sp_atk',desc:'+1 sp.atk.',price:350,holdable:false,battle:true,sprite:'assets/sprites/items/x-sp-atk.png'},
    {id:54,name:'X Sp. Def',category:'battle_item',subcategory:'stat',effect:'boost_sp_def',desc:'+1 sp.def.',price:350,holdable:false,battle:true,sprite:'assets/sprites/items/x-sp-def.png'},
    {id:55,name:'Dire Hit',category:'battle_item',subcategory:'crit',effect:'boost_crit',desc:'Aumenta chance de crit.',price:650,holdable:false,battle:true,sprite:'assets/sprites/items/dire-hit.png'},
    {id:60,name:'Escape Rope',category:'field',subcategory:'escape',effect:'escape',desc:'Sai de cavernas.',price:550,holdable:false,battle:false,sprite:'assets/sprites/items/escape-rope.png'},
    {id:70,name:'Exp Candy XS',category:'medicine',subcategory:'exp',effect:'exp_100',effect_value:100,desc:'+100 EXP.',price:0,holdable:false,battle:false,sprite:'assets/sprites/items/exp-candy-xs.png'},
    {id:71,name:'Exp Candy S',category:'medicine',subcategory:'exp',effect:'exp_500',effect_value:500,desc:'+500 EXP.',price:0,holdable:false,battle:false,sprite:'assets/sprites/items/exp-candy-s.png'},
    {id:72,name:'Exp Candy M',category:'medicine',subcategory:'exp',effect:'exp_1200',effect_value:1200,desc:'+1200 EXP.',price:0,holdable:false,battle:false,sprite:'assets/sprites/items/exp-candy-m.png'},
    {id:73,name:'Exp Candy L',category:'medicine',subcategory:'exp',effect:'exp_3000',effect_value:3000,desc:'+3000 EXP.',price:0,holdable:false,battle:false,sprite:'assets/sprites/items/exp-candy-l.png'},
    {id:74,name:'Exp Candy XL',category:'medicine',subcategory:'exp',effect:'exp_10000',effect_value:10000,desc:'+10000 EXP.',price:0,holdable:false,battle:false,sprite:'assets/sprites/items/exp-candy-xl.png'},
    {id:80,name:'HP Up',category:'medicine',subcategory:'ev',effect:'ev_hp',effect_value:1,desc:'+1 EV HP por uso.',price:10000,holdable:false,battle:false,sprite:'assets/sprites/items/hp-up.png'},
    {id:81,name:'Protein',category:'medicine',subcategory:'ev',effect:'ev_attack',effect_value:1,desc:'+1 EV Ataque.',price:10000,holdable:false,battle:false,sprite:'assets/sprites/items/protein.png'},
    {id:82,name:'Iron',category:'medicine',subcategory:'ev',effect:'ev_defense',effect_value:1,desc:'+1 EV Defesa.',price:10000,holdable:false,battle:false,sprite:'assets/sprites/items/iron.png'},
    {id:83,name:'Zinc',category:'medicine',subcategory:'ev',effect:'ev_sp_atk',effect_value:1,desc:'+1 EV Sp.Atk.',price:10000,holdable:false,battle:false,sprite:'assets/sprites/items/zinc.png'},
    {id:84,name:'Calcium',category:'medicine',subcategory:'ev',effect:'ev_sp_def',effect_value:1,desc:'+1 EV Sp.Def.',price:10000,holdable:false,battle:false,sprite:'assets/sprites/items/calcium.png'},
    {id:85,name:'Carbos',category:'medicine',subcategory:'ev',effect:'ev_speed',effect_value:1,desc:'+1 EV Speed.',price:10000,holdable:false,battle:false,sprite:'assets/sprites/items/carbos.png'}
];

const EVOLUTION_STONES = [
    {id:100,name:'Fire Stone',category:'evolution_stone',effect:'evolve_fire',desc:'Evolui Vulpix, Growlithe, Eevee.',price:2100,holdable:false,sprite:'assets/sprites/items/fire-stone.png'},
    {id:101,name:'Water Stone',category:'evolution_stone',effect:'evolve_water',desc:'Evolui Poliwhirl, Shellder, Staryu, Eevee.',price:2100,holdable:false,sprite:'assets/sprites/items/water-stone.png'},
    {id:102,name:'Thunder Stone',category:'evolution_stone',effect:'evolve_thunder',desc:'Evolui Pikachu, Eevee.',price:2100,holdable:false,sprite:'assets/sprites/items/thunder-stone.png'},
    {id:103,name:'Leaf Stone',category:'evolution_stone',effect:'evolve_grass',desc:'Evolui Gloom, Weepinbell, Exeggcute.',price:2100,holdable:false,sprite:'assets/sprites/items/leaf-stone.png'},
    {id:104,name:'Ice Stone',category:'evolution_stone',effect:'evolve_ice',desc:'Evolui Alolan Vulpix, Alolan Sandshrew.',price:2100,holdable:false,sprite:'assets/sprites/items/ice-stone.png'},
    {id:105,name:'Moon Stone',category:'evolution_stone',effect:'evolve_moon',desc:'Evolui Nidorina, Nidorino, Clefairy, Jigglypuff.',price:2100,holdable:false,sprite:'assets/sprites/items/moon-stone.png'},
    {id:106,name:'Sun Stone',category:'evolution_stone',effect:'evolve_sun',desc:'Evolui Gloom, Cottonee, Petilil.',price:2100,holdable:false,sprite:'assets/sprites/items/sun-stone.png'},
    {id:107,name:'Shiny Stone',category:'evolution_stone',effect:'evolve_shiny',desc:'Evolui Togetic, Roselia, Minccino.',price:2100,holdable:false,sprite:'assets/sprites/items/shiny-stone.png'},
    {id:108,name:'Dusk Stone',category:'evolution_stone',effect:'evolve_dusk',desc:'Evolui Murkrow, Lampent, Doublade.',price:2100,holdable:false,sprite:'assets/sprites/items/dusk-stone.png'},
    {id:109,name:'Dawn Stone',category:'evolution_stone',effect:'evolve_dawn',desc:'Evolui Male Kirlia, Female Snorunt.',price:2100,holdable:false,sprite:'assets/sprites/items/dawn-stone.png'},
    {id:110,name:'Oval Stone',category:'evolution_stone',effect:'evolve_oval',desc:'Evolui Happiny com amizade+dia.',price:2100,holdable:false,sprite:'assets/sprites/items/oval-stone.png'},
    {id:111,name:'Sweet Apple',category:'evolution_stone',effect:'evolve_sweet',desc:'Evolui Applin em Appletun.',price:2200,holdable:false,sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sweet-apple.png'},
    {id:112,name:'Tart Apple',category:'evolution_stone',effect:'evolve_tart',desc:'Evolui Applin em Flapple.',price:2200,holdable:false,sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tart-apple.png'}
];

const HELD_ITEMS = [
    {id:201,name:'Leftovers',category:'held',subcategory:'recovery',effect:'leftovers',desc:'Cura 1/16 HP por turno.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/leftovers.png'},
    {id:202,name:'Choice Band',category:'held',subcategory:'offensive',effect:'choice_band',desc:'+50% ATK, fixa 1 golpe.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/choice-band.png'},
    {id:203,name:'Choice Specs',category:'held',subcategory:'offensive',effect:'choice_specs',desc:'+50% SP.ATK, fixa 1 golpe.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/choice-specs.png'},
    {id:204,name:'Choice Scarf',category:'held',subcategory:'speed',effect:'choice_scarf',desc:'+50% SPEED, fixa 1 golpe.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/choice-scarf.png'},
    {id:205,name:'Life Orb',category:'held',subcategory:'offensive',effect:'life_orb',desc:'+30% dano, -10% HP por ataque.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/life-orb.png'},
    {id:206,name:'Focus Sash',category:'held',subcategory:'defensive',effect:'focus_sash',desc:'Sobrevive com 1 HP (1x).',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/focus-sash.png'},
    {id:207,name:'Expert Belt',category:'held',subcategory:'offensive',effect:'expert_belt',desc:'+20% em golpes SE.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/expert-belt.png'},
    {id:208,name:'Rocky Helmet',category:'held',subcategory:'defensive',effect:'rocky_helmet',desc:'Machuca atacante em 1/6 HP.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/rocky-helmet.png'},
    {id:209,name:'Shell Bell',category:'held',subcategory:'recovery',effect:'shell_bell',desc:'Cura 1/8 do dano causado.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/shell-bell.png'},
    {id:210,name:'Assault Vest',category:'held',subcategory:'defensive',effect:'assault_vest',desc:'+50% SP.DEF, sem status.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/assault-vest.png'},
    {id:211,name:'Eviolite',category:'held',subcategory:'defensive',effect:'eviolite',desc:'+50% DEF/SP.DEF (pré-evo).',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/eviolite.png'},
    {id:212,name:'Macho Brace',category:'held',subcategory:'ev',effect:'macho_brace',desc:'Dobra EVs, -50% Speed.',price:0,holdable:true,battle:false,sprite:'assets/sprites/items/macho-brace.png'},
    {id:213,name:'Power Weight',category:'held',subcategory:'ev',effect:'power_weight',desc:'+4 EVs HP, -50% Speed.',price:3200,holdable:true,battle:false,sprite:'assets/sprites/items/power-weight.png'},
    {id:214,name:'Power Bracer',category:'held',subcategory:'ev',effect:'power_bracer',desc:'+4 EVs ATK, -50% Speed.',price:3200,holdable:true,battle:false,sprite:'assets/sprites/items/power-bracer.png'},
    {id:215,name:'Power Belt',category:'held',subcategory:'ev',effect:'power_belt',desc:'+4 EVs DEF, -50% Speed.',price:3200,holdable:true,battle:false,sprite:'assets/sprites/items/power-belt.png'},
    {id:216,name:'Power Lens',category:'held',subcategory:'ev',effect:'power_lens',desc:'+4 EVs SP.ATK, -50% Speed.',price:3200,holdable:true,battle:false,sprite:'assets/sprites/items/power-lens.png'},
    {id:217,name:'Power Band',category:'held',subcategory:'ev',effect:'power_band',desc:'+4 EVs SP.DEF, -50% Speed.',price:3200,holdable:true,battle:false,sprite:'assets/sprites/items/power-band.png'},
    {id:218,name:'Power Anklet',category:'held',subcategory:'ev',effect:'power_anklet',desc:'+4 EVs SPD, -50% Speed.',price:3200,holdable:true,battle:false,sprite:'assets/sprites/items/power-anklet.png'},
    {id:219,name:'Lucky Egg',category:'held',subcategory:'exp',effect:'lucky_egg',desc:'+50% EXP.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/lucky-egg.png'},
    {id:220,name:'Amulet Coin',category:'held',subcategory:'money',effect:'amulet_coin',desc:'Dobra dinheiro.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/amulet-coin.png'},
    {id:221,name:'Quick Claw',category:'held',subcategory:'priority',effect:'quick_claw',desc:'20% de atacar primeiro.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/quick-claw.png'},
    {id:222,name:'Focus Band',category:'held',subcategory:'defensive',effect:'focus_band',desc:'30% sobrevive 1 HP.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/focus-band.png'},
    {id:223,name:'Wide Lens',category:'held',subcategory:'accuracy',effect:'wide_lens',desc:'+10% acerto.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/wide-lens.png'},
    {id:224,name:'Muscle Band',category:'held',subcategory:'offensive',effect:'muscle_band',desc:'+10% golpes físicos.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/muscle-band.png'},
    {id:225,name:'Wise Glasses',category:'held',subcategory:'offensive',effect:'wise_glasses',desc:'+10% golpes especiais.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/wise-glasses.png'},
    {id:226,name:'Smoke Ball',category:'held',subcategory:'utility',effect:'smoke_ball',desc:'Fuga garantida.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/smoke-ball.png'},
    {id:227,name:'Lum Berry',category:'held',subcategory:'berry',effect:'lum_berry',desc:'Cura status uma vez.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/lum-berry.png'},
    {id:228,name:'Sitrus Berry',category:'held',subcategory:'berry',effect:'sitrus_berry',desc:'Cura 25% HP (1x, <50% HP).',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/sitrus-berry.png'},
    {id:229,name:'Oran Berry',category:'held',subcategory:'berry',effect:'oran_berry',desc:'Cura 10 HP (1x).',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/oran-berry.png'},
    {id:230,name:'Figy Berry',category:'held',subcategory:'berry',effect:'figy_berry',desc:'Cura 33% HP mas confunde.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/figy-berry.png'},
    {id:231,name:'Wiki Berry',category:'held',subcategory:'berry',effect:'wiki_berry',desc:'Cura 33% HP mas confunde.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/wiki-berry.png'},
    {id:232,name:'Mago Berry',category:'held',subcategory:'berry',effect:'mago_berry',desc:'Cura 33% HP mas confunde.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/mago-berry.png'},
    {id:233,name:'Aguav Berry',category:'held',subcategory:'berry',effect:'aguav_berry',desc:'Cura 33% HP mas confunde.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/aguav-berry.png'},
    {id:234,name:'Iapapa Berry',category:'held',subcategory:'berry',effect:'iapapa_berry',desc:'Cura 33% HP mas confunde.',price:0,holdable:true,battle:true,sprite:'assets/sprites/items/iapapa-berry.png'}
];

const MEGA_STONE_ITEMS = [
    {id:1001,name:'Venusaurite',category:'mega_stone',effect:'mega_venusaur',desc:'Mega-evolui Venusaur.',price:0,holdable:true,sprite:'assets/sprites/items/venusaurite.png'},
    {id:1002,name:'Charizardite X',category:'mega_stone',effect:'mega_charizard_x',desc:'Mega-evolui Charizard X.',price:0,holdable:true,sprite:'assets/sprites/items/charizardite-x.png'},
    {id:1003,name:'Charizardite Y',category:'mega_stone',effect:'mega_charizard_y',desc:'Mega-evolui Charizard Y.',price:0,holdable:true,sprite:'assets/sprites/items/charizardite-y.png'},
    {id:1004,name:'Blastoisinite',category:'mega_stone',effect:'mega_blastoise',desc:'Mega-evolui Blastoise.',price:0,holdable:true,sprite:'assets/sprites/items/blastoisinite.png'},
    {id:1005,name:'Alakazite',category:'mega_stone',effect:'mega_alakazam',desc:'Mega-evolui Alakazam.',price:0,holdable:true,sprite:'assets/sprites/items/alakazite.png'},
    {id:1006,name:'Gengarite',category:'mega_stone',effect:'mega_gengar',desc:'Mega-evolui Gengar.',price:0,holdable:true,sprite:'assets/sprites/items/gengarite.png'},
    {id:1007,name:'Kangaskhanite',category:'mega_stone',effect:'mega_kangaskhan',desc:'Mega-evolui Kangaskhan.',price:0,holdable:true,sprite:'assets/sprites/items/kangaskhanite.png'},
    {id:1008,name:'Pinsirite',category:'mega_stone',effect:'mega_pinsir',desc:'Mega-evolui Pinsir.',price:0,holdable:true,sprite:'assets/sprites/items/pinsirite.png'},
    {id:1009,name:'Gyaradosite',category:'mega_stone',effect:'mega_gyarados',desc:'Mega-evolui Gyarados.',price:0,holdable:true,sprite:'assets/sprites/items/gyaradosite.png'},
    {id:1010,name:'Aerodactylite',category:'mega_stone',effect:'mega_aerodactyl',desc:'Mega-evolui Aerodactyl.',price:0,holdable:true,sprite:'assets/sprites/items/aerodactylite.png'},
    {id:1011,name:'Mewtwonite X',category:'mega_stone',effect:'mega_mewtwo_x',desc:'Mega-evolui Mewtwo X.',price:0,holdable:true,sprite:'assets/sprites/items/mewtwonite-x.png'},
    {id:1012,name:'Mewtwonite Y',category:'mega_stone',effect:'mega_mewtwo_y',desc:'Mega-evolui Mewtwo Y.',price:0,holdable:true,sprite:'assets/sprites/items/mewtwonite-y.png'},
    {id:1013,name:'Scizorite',category:'mega_stone',effect:'mega_scizor',desc:'Mega-evolui Scizor.',price:0,holdable:true,sprite:'assets/sprites/items/scizorite.png'},
    {id:1014,name:'Heracronite',category:'mega_stone',effect:'mega_heracross',desc:'Mega-evolui Heracross.',price:0,holdable:true,sprite:'assets/sprites/items/heracronite.png'},
    {id:1015,name:'Houndoominite',category:'mega_stone',effect:'mega_houndoom',desc:'Mega-evolui Houndoom.',price:0,holdable:true,sprite:'assets/sprites/items/houndoominite.png'},
    {id:1016,name:'Tyranitarite',category:'mega_stone',effect:'mega_tyranitar',desc:'Mega-evolui Tyranitar.',price:0,holdable:true,sprite:'assets/sprites/items/tyranitarite.png'},
    {id:1017,name:'Blazikenite',category:'mega_stone',effect:'mega_blaziken',desc:'Mega-evolui Blaziken.',price:0,holdable:true,sprite:'assets/sprites/items/blazikenite.png'},
    {id:1018,name:'Gardevoirite',category:'mega_stone',effect:'mega_gardevoir',desc:'Mega-evolui Gardevoir.',price:0,holdable:true,sprite:'assets/sprites/items/gardevoirite.png'},
    {id:1019,name:'Mawhite',category:'mega_stone',effect:'mega_mawile',desc:'Mega-evolui Mawile.',price:0,holdable:true,sprite:'assets/sprites/items/mawilite.png'},
    {id:1020,name:'Aggronite',category:'mega_stone',effect:'mega_aggron',desc:'Mega-evolui Aggron.',price:0,holdable:true,sprite:'assets/sprites/items/aggronite.png'},
    {id:1021,name:'Manectite',category:'mega_stone',effect:'mega_manectric',desc:'Mega-evolui Manectric.',price:0,holdable:true,sprite:'assets/sprites/items/manectite.png'},
    {id:1022,name:'Garchompite',category:'mega_stone',effect:'mega_garchomp',desc:'Mega-evolui Garchomp.',price:0,holdable:true,sprite:'assets/sprites/items/garchompite.png'},
    {id:1023,name:'Lucarionite',category:'mega_stone',effect:'mega_lucario',desc:'Mega-evolui Lucario.',price:0,holdable:true,sprite:'assets/sprites/items/lucarionite.png'},
    {id:1024,name:'Abomasite',category:'mega_stone',effect:'mega_abomasnow',desc:'Mega-evolui Abomasnow.',price:0,holdable:true,sprite:'assets/sprites/items/abomasite.png'},
    {id:1025,name:'Beedrillite',category:'mega_stone',effect:'mega_beedrill',desc:'Mega-evolui Beedrill.',price:0,holdable:true,sprite:'assets/sprites/items/beedrillite.png'},
    {id:1026,name:'Pidgeotite',category:'mega_stone',effect:'mega_pidgeot',desc:'Mega-evolui Pidgeot.',price:0,holdable:true,sprite:'assets/sprites/items/pidgeotite.png'},
    {id:1027,name:'Slowbronite',category:'mega_stone',effect:'mega_slowbro',desc:'Mega-evolui Slowbro.',price:0,holdable:true,sprite:'assets/sprites/items/slowbronite.png'},
    {id:1028,name:'Steelixite',category:'mega_stone',effect:'mega_steelix',desc:'Mega-evolui Steelix.',price:0,holdable:true,sprite:'assets/sprites/items/steelixite.png'},
    {id:1029,name:'Sharpedonite',category:'mega_stone',effect:'mega_sharpedo',desc:'Mega-evolui Sharpedo.',price:0,holdable:true,sprite:'assets/sprites/items/sharpedonite.png'},
    {id:1030,name:'Cameruptite',category:'mega_stone',effect:'mega_camerupt',desc:'Mega-evolui Camerupt.',price:0,holdable:true,sprite:'assets/sprites/items/cameruptite.png'},
    {id:1031,name:'Altarianite',category:'mega_stone',effect:'mega_altaria',desc:'Mega-evolui Altaria.',price:0,holdable:true,sprite:'assets/sprites/items/altarianite.png'},
    {id:1032,name:'Salamencite',category:'mega_stone',effect:'mega_salamence',desc:'Mega-evolui Salamence.',price:0,holdable:true,sprite:'assets/sprites/items/salamencite.png'},
    {id:1033,name:'Metagrossite',category:'mega_stone',effect:'mega_metagross',desc:'Mega-evolui Metagross.',price:0,holdable:true,sprite:'assets/sprites/items/metagrossite.png'},
    {id:1034,name:'Latiasite',category:'mega_stone',effect:'mega_latias',desc:'Mega-evolui Latias.',price:0,holdable:true,sprite:'assets/sprites/items/latiasite.png'},
    {id:1035,name:'Latiosite',category:'mega_stone',effect:'mega_latios',desc:'Mega-evolui Latios.',price:0,holdable:true,sprite:'assets/sprites/items/latiosite.png'},
    {id:1036,name:'Rayquazite',category:'mega_stone',effect:'mega_rayquaza',desc:'Mega-evolui Rayquaza.',price:0,holdable:true,sprite:'assets/sprites/items/rayquazite.png'},
    {id:1037,name:'Lopunnite',category:'mega_stone',effect:'mega_lopunny',desc:'Mega-evolui Lopunny.',price:0,holdable:true,sprite:'assets/sprites/items/lopunnite.png'},
    {id:1038,name:'Galladite',category:'mega_stone',effect:'mega_gallade',desc:'Mega-evolui Gallade.',price:0,holdable:true,sprite:'assets/sprites/items/galladite.png'},
    {id:1039,name:'Audinite',category:'mega_stone',effect:'mega_audino',desc:'Mega-evolui Audino.',price:0,holdable:true,sprite:'assets/sprites/items/audinite.png'},
    {id:1040,name:'Diancite',category:'mega_stone',effect:'mega_diancie',desc:'Mega-evolui Diancie.',price:0,holdable:true,sprite:'assets/sprites/items/diancite.png'},
    {id:1041,name:'Sceptilite',category:'mega_stone',effect:'mega_sceptile',desc:'Mega-evolui Sceptile.',price:0,holdable:true,sprite:'assets/sprites/items/sceptilite.png'},
    {id:1042,name:'Swampertite',category:'mega_stone',effect:'mega_swampert',desc:'Mega-evolui Swampert.',price:0,holdable:true,sprite:'assets/sprites/items/swampertite.png'},
    {id:1043,name:'Banettite',category:'mega_stone',effect:'mega_banette',desc:'Mega-evolui Banette.',price:0,holdable:true,sprite:'assets/sprites/items/banettite.png'},
    {id:1044,name:'Absolite',category:'mega_stone',effect:'mega_absol',desc:'Mega-evolui Absol.',price:0,holdable:true,sprite:'assets/sprites/items/absolite.png'},
    {id:1045,name:'Sableyenite',category:'mega_stone',effect:'mega_sableye',desc:'Mega-evolui Sableye.',price:0,holdable:true,sprite:'assets/sprites/items/sableyenite.png'},
    {id:1046,name:'Glalitite',category:'mega_stone',effect:'mega_glalie',desc:'Mega-evolui Glalie.',price:0,holdable:true,sprite:'assets/sprites/items/glalitite.png'}
];

window.ALL_ITEMS = [...ITEMS_DATA, ...EVOLUTION_STONES, ...HELD_ITEMS, ...MEGA_STONE_ITEMS];
