ALTER TABLE region_maps ADD COLUMN IF NOT EXISTS battle_player_x NUMERIC DEFAULT 0.25;
ALTER TABLE region_maps ADD COLUMN IF NOT EXISTS battle_player_y NUMERIC DEFAULT 0.75;
ALTER TABLE region_maps ADD COLUMN IF NOT EXISTS battle_enemy_x NUMERIC DEFAULT 0.72;
ALTER TABLE region_maps ADD COLUMN IF NOT EXISTS battle_enemy_y NUMERIC DEFAULT 0.4;
ALTER TABLE region_maps ADD COLUMN IF NOT EXISTS battle_player_fx TEXT DEFAULT 'none';
ALTER TABLE region_maps ADD COLUMN IF NOT EXISTS battle_enemy_fx TEXT DEFAULT 'none';
