-- =============================================
-- SEED: TRs (Gen 8 - Sword/Shield) IDs 4000-4099
-- =============================================

INSERT INTO items (id, name, category, subcategory, effect, effect_value, description, price, sprite_url, holdable, usable_in_battle) VALUES
(4000, 'TR00 Swords Dance', 'tr', 'normal', 'learn_move', 0, 'Ensin Swords Dance.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4001, 'TR01 Body Slam', 'tr', 'normal', 'learn_move', 0, 'Ensin Body Slam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4002, 'TR02 Flamethrower', 'tr', 'fire', 'learn_move', 0, 'Ensin Flamethrower.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(4003, 'TR03 Hydro Pump', 'tr', 'water', 'learn_move', 0, 'Ensin Hydro Pump.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(4004, 'TR04 Surf', 'tr', 'water', 'learn_move', 0, 'Ensin Surf.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(4005, 'TR05 Ice Beam', 'tr', 'ice', 'learn_move', 0, 'Ensin Ice Beam.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
(4006, 'TR06 Blizzard', 'tr', 'ice', 'learn_move', 0, 'Ensin Blizzard.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
(4007, 'TR07 Low Kick', 'tr', 'fighting', 'learn_move', 0, 'Ensin Low Kick.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(4008, 'TR08 Thunderbolt', 'tr', 'electric', 'learn_move', 0, 'Ensin Thunderbolt.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(4009, 'TR09 Thunder', 'tr', 'electric', 'learn_move', 0, 'Ensin Thunder.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(4010, 'TR10 Earthquake', 'tr', 'ground', 'learn_move', 0, 'Ensin Earthquake.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(4011, 'TR11 Psychic', 'tr', 'psychic', 'learn_move', 0, 'Ensin Psychic.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4012, 'TR12 Agility', 'tr', 'psychic', 'learn_move', 0, 'Ensin Agility.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4013, 'TR13 Focus Energy', 'tr', 'normal', 'learn_move', 0, 'Ensin Focus Energy.', 1000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4014, 'TR14 Metronome', 'tr', 'normal', 'learn_move', 0, 'Ensin Metronome.', 1000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4015, 'TR15 Fire Blast', 'tr', 'fire', 'learn_move', 0, 'Ensin Fire Blast.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(4016, 'TR16 Waterfall', 'tr', 'water', 'learn_move', 0, 'Ensin Waterfall.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(4017, 'TR17 Amnesia', 'tr', 'psychic', 'learn_move', 0, 'Ensin Amnesia.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4018, 'TR18 Leech Life', 'tr', 'bug', 'learn_move', 0, 'Ensin Leech Life.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(4019, 'TR19 Tri Attack', 'tr', 'normal', 'learn_move', 0, 'Ensin Tri Attack.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4020, 'TR20 Substitute', 'tr', 'normal', 'learn_move', 0, 'Ensin Substitute.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4021, 'TR21 Reversal', 'tr', 'fighting', 'learn_move', 0, 'Ensin Reversal.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(4022, 'TR22 Sludge Bomb', 'tr', 'poison', 'learn_move', 0, 'Ensin Sludge Bomb.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(4023, 'TR23 Spikes', 'tr', 'ground', 'learn_move', 0, 'Ensin Spikes.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(4024, 'TR24 Outrage', 'tr', 'dragon', 'learn_move', 0, 'Ensin Outrage.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
(4025, 'TR25 Psyshock', 'tr', 'psychic', 'learn_move', 0, 'Ensin Psyshock.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4026, 'TR26 Endure', 'tr', 'normal', 'learn_move', 0, 'Ensin Endure.', 1000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4027, 'TR27 Sleep Talk', 'tr', 'normal', 'learn_move', 0, 'Ensin Sleep Talk.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4028, 'TR28 Megahorn', 'tr', 'bug', 'learn_move', 0, 'Ensin Megahorn.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(4029, 'TR29 Baton Pass', 'tr', 'normal', 'learn_move', 0, 'Ensin Baton Pass.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4030, 'TR30 Encore', 'tr', 'normal', 'learn_move', 0, 'Ensin Encore.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4031, 'TR31 Iron Tail', 'tr', 'steel', 'learn_move', 0, 'Ensin Iron Tail.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(4032, 'TR32 Crunch', 'tr', 'dark', 'learn_move', 0, 'Ensin Crunch.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(4033, 'TR33 Shadow Ball', 'tr', 'ghost', 'learn_move', 0, 'Ensin Shadow Ball.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ghost.png', false, false),
(4034, 'TR34 Future Sight', 'tr', 'psychic', 'learn_move', 0, 'Ensin Future Sight.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4035, 'TR35 Uproar', 'tr', 'normal', 'learn_move', 0, 'Ensin Uproar.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4036, 'TR36 Heat Wave', 'tr', 'fire', 'learn_move', 0, 'Ensin Heat Wave.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(4037, 'TR37 Taunt', 'tr', 'dark', 'learn_move', 0, 'Ensin Taunt.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(4038, 'TR38 Trick', 'tr', 'psychic', 'learn_move', 0, 'Ensin Trick.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4039, 'TR39 Superpower', 'tr', 'fighting', 'learn_move', 0, 'Ensin Superpower.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(4040, 'TR40 Skill Swap', 'tr', 'psychic', 'learn_move', 0, 'Ensin Skill Swap.', 1000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4041, 'TR41 Blaze Kick', 'tr', 'fire', 'learn_move', 0, 'Ensin Blaze Kick.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(4042, 'TR42 Hyper Voice', 'tr', 'normal', 'learn_move', 0, 'Ensin Hyper Voice.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4043, 'TR43 Overheat', 'tr', 'fire', 'learn_move', 0, 'Ensin Overheat.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(4044, 'TR44 Cosmic Power', 'tr', 'psychic', 'learn_move', 0, 'Ensin Cosmic Power.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4045, 'TR45 Muddy Water', 'tr', 'water', 'learn_move', 0, 'Ensin Muddy Water.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(4046, 'TR46 Iron Defense', 'tr', 'steel', 'learn_move', 0, 'Ensin Iron Defense.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(4047, 'TR47 Dragon Claw', 'tr', 'dragon', 'learn_move', 0, 'Ensin Dragon Claw.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
(4048, 'TR48 Bulk Up', 'tr', 'fighting', 'learn_move', 0, 'Ensin Bulk Up.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(4049, 'TR49 Calm Mind', 'tr', 'psychic', 'learn_move', 0, 'Ensin Calm Mind.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4050, 'TR50 Leaf Blade', 'tr', 'grass', 'learn_move', 0, 'Ensin Leaf Blade.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(4051, 'TR51 Dragon Dance', 'tr', 'dragon', 'learn_move', 0, 'Ensin Dragon Dance.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
(4052, 'TR52 Gyro Ball', 'tr', 'steel', 'learn_move', 0, 'Ensin Gyro Ball.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(4053, 'TR53 Close Combat', 'tr', 'fighting', 'learn_move', 0, 'Ensin Close Combat.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(4054, 'TR54 Toxic Spikes', 'tr', 'poison', 'learn_move', 0, 'Ensin Toxic Spikes.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(4055, 'TR55 Flare Blitz', 'tr', 'fire', 'learn_move', 0, 'Ensin Flare Blitz.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(4056, 'TR56 Aura Sphere', 'tr', 'fighting', 'learn_move', 0, 'Ensin Aura Sphere.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(4057, 'TR57 Poison Jab', 'tr', 'poison', 'learn_move', 0, 'Ensin Poison Jab.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(4058, 'TR58 Dark Pulse', 'tr', 'dark', 'learn_move', 0, 'Ensin Dark Pulse.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(4059, 'TR59 Seed Bomb', 'tr', 'grass', 'learn_move', 0, 'Ensin Seed Bomb.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(4060, 'TR60 X-Scissor', 'tr', 'bug', 'learn_move', 0, 'Ensin X-Scissor.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(4061, 'TR61 Bug Buzz', 'tr', 'bug', 'learn_move', 0, 'Ensin Bug Buzz.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(4062, 'TR62 Dragon Pulse', 'tr', 'dragon', 'learn_move', 0, 'Ensin Dragon Pulse.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
(4063, 'TR63 Power Gem', 'tr', 'rock', 'learn_move', 0, 'Ensin Power Gem.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-rock.png', false, false),
(4064, 'TR64 Focus Blast', 'tr', 'fighting', 'learn_move', 0, 'Ensin Focus Blast.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(4065, 'TR65 Energy Ball', 'tr', 'grass', 'learn_move', 0, 'Ensin Energy Ball.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(4066, 'TR66 Brave Bird', 'tr', 'flying', 'learn_move', 0, 'Ensin Brave Bird.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-flying.png', false, false),
(4067, 'TR67 Earth Power', 'tr', 'ground', 'learn_move', 0, 'Ensin Earth Power.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(4068, 'TR68 Nasty Plot', 'tr', 'dark', 'learn_move', 0, 'Ensin Nasty Plot.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(4069, 'TR69 Zen Headbutt', 'tr', 'psychic', 'learn_move', 0, 'Ensin Zen Headbutt.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4070, 'TR70 Flash Cannon', 'tr', 'steel', 'learn_move', 0, 'Ensin Flash Cannon.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(4071, 'TR71 Leaf Storm', 'tr', 'grass', 'learn_move', 0, 'Ensin Leaf Storm.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(4072, 'TR72 Power Whip', 'tr', 'grass', 'learn_move', 0, 'Ensin Power Whip.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(4073, 'TR73 Gunk Shot', 'tr', 'poison', 'learn_move', 0, 'Ensin Gunk Shot.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(4074, 'TR74 Iron Head', 'tr', 'steel', 'learn_move', 0, 'Ensin Iron Head.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(4075, 'TR75 Stone Edge', 'tr', 'rock', 'learn_move', 0, 'Ensin Stone Edge.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-rock.png', false, false),
(4076, 'TR76 Stealth Rock', 'tr', 'rock', 'learn_move', 0, 'Ensin Stealth Rock.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-rock.png', false, false),
(4077, 'TR77 Grass Knot', 'tr', 'grass', 'learn_move', 0, 'Ensin Grass Knot.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(4078, 'TR78 Sludge Wave', 'tr', 'poison', 'learn_move', 0, 'Ensin Sludge Wave.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(4079, 'TR79 Heavy Slam', 'tr', 'steel', 'learn_move', 0, 'Ensin Heavy Slam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(4080, 'TR80 Electro Ball', 'tr', 'electric', 'learn_move', 0, 'Ensin Electro Ball.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(4081, 'TR81 Foul Play', 'tr', 'dark', 'learn_move', 0, 'Ensin Foul Play.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(4082, 'TR82 Stored Power', 'tr', 'psychic', 'learn_move', 0, 'Ensin Stored Power.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4083, 'TR83 Ally Switch', 'tr', 'psychic', 'learn_move', 0, 'Ensin Ally Switch.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4084, 'TR84 Scald', 'tr', 'water', 'learn_move', 0, 'Ensin Scald.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(4085, 'TR85 Work Up', 'tr', 'normal', 'learn_move', 0, 'Ensin Work Up.', 1000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(4086, 'TR86 Wild Charge', 'tr', 'electric', 'learn_move', 0, 'Ensin Wild Charge.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(4087, 'TR87 Drill Run', 'tr', 'ground', 'learn_move', 0, 'Ensin Drill Run.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(4088, 'TR88 Heat Crash', 'tr', 'fire', 'learn_move', 0, 'Ensin Heat Crash.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(4089, 'TR89 Hurricane', 'tr', 'flying', 'learn_move', 0, 'Ensin Hurricane.', 8000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-flying.png', false, false),
(4090, 'TR90 Play Rough', 'tr', 'fairy', 'learn_move', 0, 'Ensin Play Rough.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fairy.png', false, false),
(4091, 'TR91 Venom Drench', 'tr', 'poison', 'learn_move', 0, 'Ensin Venom Drench.', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(4092, 'TR92 Dazzling Gleam', 'tr', 'fairy', 'learn_move', 0, 'Ensin Dazzling Gleam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fairy.png', false, false),
(4093, 'TR93 Darkest Lariat', 'tr', 'dark', 'learn_move', 0, 'Ensin Darkest Lariat.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(4094, 'TR94 High Horsepower', 'tr', 'ground', 'learn_move', 0, 'Ensin High Horsepower.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(4095, 'TR95 Throat Chop', 'tr', 'dark', 'learn_move', 0, 'Ensin Throat Chop.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(4096, 'TR96 Pollen Puff', 'tr', 'bug', 'learn_move', 0, 'Ensin Pollen Puff.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(4097, 'TR97 Psychic Fangs', 'tr', 'psychic', 'learn_move', 0, 'Ensin Psychic Fangs.', 5000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(4098, 'TR98 Liquidation', 'tr', 'water', 'learn_move', 0, 'Ensin Liquidation.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(4099, 'TR99 Body Press', 'tr', 'fighting', 'learn_move', 0, 'Ensin Body Press.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false)

ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    effect = EXCLUDED.effect,
    effect_value = EXCLUDED.effect_value,
    description = EXCLUDED.description,
    price = EXCLUDED.price,
    sprite_url = EXCLUDED.sprite_url,
    holdable = EXCLUDED.holdable,
    usable_in_battle = EXCLUDED.usable_in_battle;

SELECT 'TRs total: ' || count(*)::text FROM items WHERE category = 'tr';
