-- Tabela de quests do Professor Carvalho
CREATE TABLE IF NOT EXISTS city_professor_quests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npc_id UUID NOT NULL REFERENCES city_npcs(id) ON DELETE CASCADE,
    order_index INTEGER NOT NULL DEFAULT 0,
    quest_type TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    target_count INTEGER DEFAULT 1,
    target_biome TEXT,
    target_pokemon_id BIGINT,
    target_pokemon_name TEXT,
    target_npc_id UUID,
    target_npc_name TEXT,
    dialogue_text TEXT,
    pvp_required BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de recompensas das quests
CREATE TABLE IF NOT EXISTS city_professor_quest_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_id BIGINT NOT NULL REFERENCES city_professor_quests(id) ON DELETE CASCADE,
    reward_type TEXT NOT NULL,
    amount INTEGER DEFAULT 0,
    pokemon_id BIGINT,
    pokemon_level INTEGER DEFAULT 5,
    nature TEXT,
    iv_hp INTEGER DEFAULT 0,
    iv_attack INTEGER DEFAULT 0,
    iv_defense INTEGER DEFAULT 0,
    iv_sp_atk INTEGER DEFAULT 0,
    iv_sp_def INTEGER DEFAULT 0,
    iv_speed INTEGER DEFAULT 0,
    ev_hp INTEGER DEFAULT 0,
    ev_attack INTEGER DEFAULT 0,
    ev_defense INTEGER DEFAULT 0,
    ev_sp_atk INTEGER DEFAULT 0,
    ev_sp_def INTEGER DEFAULT 0,
    ev_speed INTEGER DEFAULT 0,
    item_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de progresso do jogador nas quests
CREATE TABLE IF NOT EXISTS player_professor_quests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    character_id UUID NOT NULL,
    npc_id UUID NOT NULL REFERENCES city_npcs(id) ON DELETE CASCADE,
    quest_id BIGINT NOT NULL REFERENCES city_professor_quests(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'locked',
    progress INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, character_id, quest_id)
);

-- Adicionar colunas que podem nao existir
DO $$ BEGIN ALTER TABLE city_professor_quests ADD COLUMN target_npc_id UUID; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quests ADD COLUMN target_npc_name TEXT; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quests ADD COLUMN dialogue_text TEXT; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN pokemon_level INTEGER DEFAULT 5; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN nature TEXT; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN iv_hp INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN iv_attack INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN iv_defense INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN iv_sp_atk INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN iv_sp_def INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN iv_speed INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN ev_hp INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN ev_attack INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN ev_defense INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN ev_sp_atk INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN ev_sp_def INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE city_professor_quest_rewards ADD COLUMN ev_speed INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
