-- Update gym leader sprite_url with official sprites
-- Generated from Smogon sprites repository

UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Brock.png' WHERE name = 'Brock';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Misty.png' WHERE name = 'Misty';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Lt__Surge.png' WHERE name = 'Lt. Surge';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Erika.png' WHERE name = 'Erika';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Koga.png' WHERE name = 'Koga';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Sabrina.png' WHERE name = 'Sabrina';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Blaine.png' WHERE name = 'Blaine';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Giovanni.png' WHERE name = 'Giovanni';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Falkner.png' WHERE name = 'Falkner';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Bugsy.png' WHERE name = 'Bugsy';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Whitney.png' WHERE name = 'Whitney';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Morty.png' WHERE name = 'Morty';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Chuck.png' WHERE name = 'Chuck';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Jasmine.png' WHERE name = 'Jasmine';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Pryce.png' WHERE name = 'Pryce';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Clair.png' WHERE name = 'Clair';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Roxanne.png' WHERE name = 'Roxanne';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Brawly.png' WHERE name = 'Brawly';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Wattson.png' WHERE name = 'Wattson';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Flannery.png' WHERE name = 'Flannery';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Norman.png' WHERE name = 'Norman';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Winona.png' WHERE name = 'Winona';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Wallace.png' WHERE name = 'Wallace';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Roark.png' WHERE name = 'Roark';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Gardenia.png' WHERE name = 'Gardenia';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Fantina.png' WHERE name = 'Fantina';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Maylene.png' WHERE name = 'Maylene';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Crasher_Wake.png' WHERE name = 'Crasher Wake';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Byron.png' WHERE name = 'Byron';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Candice.png' WHERE name = 'Candice';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Volkner.png' WHERE name = 'Volkner';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Cilan.png' WHERE name = 'Cilan';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Lenora.png' WHERE name = 'Lenora';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Burgh.png' WHERE name = 'Burgh';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Elesa.png' WHERE name = 'Elesa';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Clay.png' WHERE name = 'Clay';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Skyla.png' WHERE name = 'Skyla';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Brycen.png' WHERE name = 'Brycen';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Drayden.png' WHERE name = 'Drayden';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Viola.png' WHERE name = 'Viola';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Korrina.png' WHERE name = 'Korrina';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Ramos.png' WHERE name = 'Ramos';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Valerie.png' WHERE name = 'Valerie';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Olympia.png' WHERE name = 'Olympia';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Wulfric.png' WHERE name = 'Wulfric';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Hala.png' WHERE name = 'Hala';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Olivia.png' WHERE name = 'Olivia';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Nanu.png' WHERE name = 'Nanu';
UPDATE gym_leaders SET sprite_url = 'https://odevwnnpzsoltbrrjdts.supabase.co/storage/v1/object/public/sprites/gym-leaders/Hapu.png' WHERE name = 'Hapu';
