-- =============================================
-- SEED: TMs (Gen 9 - Scarlet/Violet) IDs 3000-3229
-- =============================================

INSERT INTO items (id, name, category, subcategory, effect, effect_value, description, price, sprite_url, holdable, usable_in_battle) VALUES
-- TM001-TM010
(3001, 'TM001 Take Down', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Take Down.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3002, 'TM002 Charm', 'tm_hm', 'fairy', 'learn_move', 0, 'Ensin Charm.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fairy.png', false, false),
(3003, 'TM003 Fake Tears', 'tm_hm', 'dark', 'learn_move', 0, 'Ensin Fake Tears.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(3004, 'TM004 Agility', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Agility.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3005, 'TM005 Mud-Slap', 'tm_hm', 'ground', 'learn_move', 0, 'Ensin Mud-Slap.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(3006, 'TM006 Scary Face', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Scary Face.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3007, 'TM007 Protect', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Protect.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3008, 'TM008 Fire Fang', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Fire Fang.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3009, 'TM009 Thunder Fang', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Thunder Fang.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3010, 'TM010 Ice Fang', 'tm_hm', 'ice', 'learn_move', 0, 'Ensin Ice Fang.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
-- TM011-TM020
(3011, 'TM011 Water Pulse', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Water Pulse.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(3012, 'TM012 Low Kick', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Low Kick.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3013, 'TM013 Acid Spray', 'tm_hm', 'poison', 'learn_move', 0, 'Ensin Acid Spray.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(3014, 'TM014 Acrobatics', 'tm_hm', 'flying', 'learn_move', 0, 'Ensin Acrobatics.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-flying.png', false, false),
(3015, 'TM015 Struggle Bug', 'tm_hm', 'bug', 'learn_move', 0, 'Ensin Struggle Bug.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(3016, 'TM016 Psybeam', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Psybeam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3017, 'TM017 Confuse Ray', 'tm_hm', 'ghost', 'learn_move', 0, 'Ensin Confuse Ray.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ghost.png', false, false),
(3018, 'TM018 Thief', 'tm_hm', 'dark', 'learn_move', 0, 'Ensin Thief.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(3019, 'TM019 Disarming Voice', 'tm_hm', 'fairy', 'learn_move', 0, 'Ensin Disarming Voice.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fairy.png', false, false),
(3020, 'TM020 Trailblaze', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Trailblaze.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
-- TM021-TM030
(3021, 'TM021 Pounce', 'tm_hm', 'bug', 'learn_move', 0, 'Ensin Pounce.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(3022, 'TM022 Chilling Water', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Chilling Water.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(3023, 'TM023 Charge Beam', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Charge Beam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3024, 'TM024 Fire Spin', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Fire Spin.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3025, 'TM025 Facade', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Facade.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3026, 'TM026 Poison Tail', 'tm_hm', 'poison', 'learn_move', 0, 'Ensin Poison Tail.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(3027, 'TM027 Aerial Ace', 'tm_hm', 'flying', 'learn_move', 0, 'Ensin Aerial Ace.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-flying.png', false, false),
(3028, 'TM028 Bulldoze', 'tm_hm', 'ground', 'learn_move', 0, 'Ensin Bulldoze.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(3029, 'TM029 Hex', 'tm_hm', 'ghost', 'learn_move', 0, 'Ensin Hex.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ghost.png', false, false),
(3030, 'TM030 Snarl', 'tm_hm', 'dark', 'learn_move', 0, 'Ensin Snarl.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
-- TM031-TM040
(3031, 'TM031 Metal Claw', 'tm_hm', 'steel', 'learn_move', 0, 'Ensin Metal Claw.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(3032, 'TM032 Swift', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Swift.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3033, 'TM033 Magical Leaf', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Magical Leaf.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3034, 'TM034 Icy Wind', 'tm_hm', 'ice', 'learn_move', 0, 'Ensin Icy Wind.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
(3035, 'TM035 Mud Shot', 'tm_hm', 'ground', 'learn_move', 0, 'Ensin Mud Shot.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(3036, 'TM036 Rock Tomb', 'tm_hm', 'rock', 'learn_move', 0, 'Ensin Rock Tomb.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-rock.png', false, false),
(3037, 'TM037 Draining Kiss', 'tm_hm', 'fairy', 'learn_move', 0, 'Ensin Draining Kiss.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fairy.png', false, false),
(3038, 'TM038 Flame Charge', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Flame Charge.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3039, 'TM039 Low Sweep', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Low Sweep.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3040, 'TM040 Air Cutter', 'tm_hm', 'flying', 'learn_move', 0, 'Ensin Air Cutter.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-flying.png', false, false),
-- TM041-TM050
(3041, 'TM041 Stored Power', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Stored Power.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3042, 'TM042 Night Shade', 'tm_hm', 'ghost', 'learn_move', 0, 'Ensin Night Shade.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ghost.png', false, false),
(3043, 'TM043 Fling', 'tm_hm', 'dark', 'learn_move', 0, 'Ensin Fling.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(3044, 'TM044 Dragon Tail', 'tm_hm', 'dragon', 'learn_move', 0, 'Ensin Dragon Tail.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
(3045, 'TM045 Venoshock', 'tm_hm', 'poison', 'learn_move', 0, 'Ensin Venoshock.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(3046, 'TM046 Avalanche', 'tm_hm', 'ice', 'learn_move', 0, 'Ensin Avalanche.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
(3047, 'TM047 Endure', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Endure.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3048, 'TM048 Volt Switch', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Volt Switch.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3049, 'TM049 Sunny Day', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Sunny Day.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3050, 'TM050 Rain Dance', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Rain Dance.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
-- TM051-TM060
(3051, 'TM051 Sandstorm', 'tm_hm', 'rock', 'learn_move', 0, 'Ensin Sandstorm.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-rock.png', false, false),
(3052, 'TM052 Snowscape', 'tm_hm', 'ice', 'learn_move', 0, 'Ensin Snowscape.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
(3053, 'TM053 Smart Strike', 'tm_hm', 'steel', 'learn_move', 0, 'Ensin Smart Strike.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(3054, 'TM054 Psyshock', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Psyshock.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3055, 'TM055 Dig', 'tm_hm', 'ground', 'learn_move', 0, 'Ensin Dig.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(3056, 'TM056 Bullet Seed', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Bullet Seed.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3057, 'TM057 False Swipe', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin False Swipe.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3058, 'TM058 Brick Break', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Brick Break.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3059, 'TM059 Zen Headbutt', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Zen Headbutt.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3060, 'TM060 U-turn', 'tm_hm', 'bug', 'learn_move', 0, 'Ensin U-turn.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
-- TM061-TM070
(3061, 'TM061 Shadow Claw', 'tm_hm', 'ghost', 'learn_move', 0, 'Ensin Shadow Claw.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ghost.png', false, false),
(3062, 'TM062 Foul Play', 'tm_hm', 'dark', 'learn_move', 0, 'Ensin Foul Play.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(3063, 'TM063 Psychic Fangs', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Psychic Fangs.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3064, 'TM064 Bulk Up', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Bulk Up.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3065, 'TM065 Air Slash', 'tm_hm', 'flying', 'learn_move', 0, 'Ensin Air Slash.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-flying.png', false, false),
(3066, 'TM066 Body Slam', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Body Slam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3067, 'TM067 Fire Punch', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Fire Punch.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3068, 'TM068 Thunder Punch', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Thunder Punch.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3069, 'TM069 Ice Punch', 'tm_hm', 'ice', 'learn_move', 0, 'Ensin Ice Punch.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
(3070, 'TM070 Sleep Talk', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Sleep Talk.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
-- TM071-TM080
(3071, 'TM071 Seed Bomb', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Seed Bomb.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3072, 'TM072 Electro Ball', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Electro Ball.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3073, 'TM073 Drain Punch', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Drain Punch.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3074, 'TM074 Reflect', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Reflect.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3075, 'TM075 Light Screen', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Light Screen.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3076, 'TM076 Rock Blast', 'tm_hm', 'rock', 'learn_move', 0, 'Ensin Rock Blast.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-rock.png', false, false),
(3077, 'TM077 Waterfall', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Waterfall.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(3078, 'TM078 Dragon Claw', 'tm_hm', 'dragon', 'learn_move', 0, 'Ensin Dragon Claw.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
(3079, 'TM079 Dazzling Gleam', 'tm_hm', 'fairy', 'learn_move', 0, 'Ensin Dazzling Gleam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fairy.png', false, false),
(3080, 'TM080 Metronome', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Metronome.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
-- TM081-TM090
(3081, 'TM081 Grass Knot', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Grass Knot.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3082, 'TM082 Thunder Wave', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Thunder Wave.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3083, 'TM083 Poison Jab', 'tm_hm', 'poison', 'learn_move', 0, 'Ensin Poison Jab.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(3084, 'TM084 Stomping Tantrum', 'tm_hm', 'ground', 'learn_move', 0, 'Ensin Stomping Tantrum.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(3085, 'TM085 Rest', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Rest.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3086, 'TM086 Rock Slide', 'tm_hm', 'rock', 'learn_move', 0, 'Ensin Rock Slide.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-rock.png', false, false),
(3087, 'TM087 Taunt', 'tm_hm', 'dark', 'learn_move', 0, 'Ensin Taunt.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(3088, 'TM088 Swords Dance', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Swords Dance.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3089, 'TM089 Body Press', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Body Press.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3090, 'TM090 Spikes', 'tm_hm', 'ground', 'learn_move', 0, 'Ensin Spikes.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
-- TM091-TM100
(3091, 'TM091 Toxic Spikes', 'tm_hm', 'poison', 'learn_move', 0, 'Ensin Toxic Spikes.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(3092, 'TM092 Imprison', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Imprison.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3093, 'TM093 Flash Cannon', 'tm_hm', 'steel', 'learn_move', 0, 'Ensin Flash Cannon.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(3094, 'TM094 Dark Pulse', 'tm_hm', 'dark', 'learn_move', 0, 'Ensin Dark Pulse.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(3095, 'TM095 Leech Life', 'tm_hm', 'bug', 'learn_move', 0, 'Ensin Leech Life.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(3096, 'TM096 Eerie Impulse', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Eerie Impulse.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3097, 'TM097 Fly', 'tm_hm', 'flying', 'learn_move', 0, 'Ensin Fly.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-flying.png', false, false),
(3098, 'TM098 Skill Swap', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Skill Swap.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3099, 'TM099 Iron Head', 'tm_hm', 'steel', 'learn_move', 0, 'Ensin Iron Head.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(3100, 'TM100 Dragon Dance', 'tm_hm', 'dragon', 'learn_move', 0, 'Ensin Dragon Dance.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
-- TM101-TM110
(3101, 'TM101 Power Gem', 'tm_hm', 'rock', 'learn_move', 0, 'Ensin Power Gem.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-rock.png', false, false),
(3102, 'TM102 Gunk Shot', 'tm_hm', 'poison', 'learn_move', 0, 'Ensin Gunk Shot.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(3103, 'TM103 Substitute', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Substitute.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3104, 'TM104 Iron Defense', 'tm_hm', 'steel', 'learn_move', 0, 'Ensin Iron Defense.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(3105, 'TM105 X-Scissor', 'tm_hm', 'bug', 'learn_move', 0, 'Ensin X-Scissor.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(3106, 'TM106 Drill Run', 'tm_hm', 'ground', 'learn_move', 0, 'Ensin Drill Run.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(3107, 'TM107 Will-O-Wisp', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Will-O-Wisp.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3108, 'TM108 Crunch', 'tm_hm', 'dark', 'learn_move', 0, 'Ensin Crunch.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(3109, 'TM109 Trick', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Trick.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3110, 'TM110 Liquidation', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Liquidation.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
-- TM111-TM120
(3111, 'TM111 Giga Drain', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Giga Drain.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3112, 'TM112 Aura Sphere', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Aura Sphere.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3113, 'TM113 Tailwind', 'tm_hm', 'flying', 'learn_move', 0, 'Ensin Tailwind.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-flying.png', false, false),
(3114, 'TM114 Shadow Ball', 'tm_hm', 'ghost', 'learn_move', 0, 'Ensin Shadow Ball.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ghost.png', false, false),
(3115, 'TM115 Dragon Pulse', 'tm_hm', 'dragon', 'learn_move', 0, 'Ensin Dragon Pulse.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
(3116, 'TM116 Stealth Rock', 'tm_hm', 'rock', 'learn_move', 0, 'Ensin Stealth Rock.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-rock.png', false, false),
(3117, 'TM117 Hyper Voice', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Hyper Voice.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3118, 'TM118 Heat Wave', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Heat Wave.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3119, 'TM119 Energy Ball', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Energy Ball.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3120, 'TM120 Psychic', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Psychic.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
-- TM121-TM130
(3121, 'TM121 Heavy Slam', 'tm_hm', 'steel', 'learn_move', 0, 'Ensin Heavy Slam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(3122, 'TM122 Encore', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Encore.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3123, 'TM123 Surf', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Surf.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(3124, 'TM124 Ice Spinner', 'tm_hm', 'ice', 'learn_move', 0, 'Ensin Ice Spinner.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
(3125, 'TM125 Flamethrower', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Flamethrower.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3126, 'TM126 Thunderbolt', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Thunderbolt.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3127, 'TM127 Play Rough', 'tm_hm', 'fairy', 'learn_move', 0, 'Ensin Play Rough.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fairy.png', false, false),
(3128, 'TM128 Amnesia', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Amnesia.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3129, 'TM129 Calm Mind', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Calm Mind.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3130, 'TM130 Helping Hand', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Helping Hand.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
-- TM131-TM140
(3131, 'TM131 Pollen Puff', 'tm_hm', 'bug', 'learn_move', 0, 'Ensin Pollen Puff.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(3132, 'TM132 Baton Pass', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Baton Pass.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3133, 'TM133 Earth Power', 'tm_hm', 'ground', 'learn_move', 0, 'Ensin Earth Power.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(3134, 'TM134 Reversal', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Reversal.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3135, 'TM135 Ice Beam', 'tm_hm', 'ice', 'learn_move', 0, 'Ensin Ice Beam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
(3136, 'TM136 Electric Terrain', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Electric Terrain.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3137, 'TM137 Grassy Terrain', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Grassy Terrain.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3138, 'TM138 Psychic Terrain', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Psychic Terrain.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3139, 'TM139 Misty Terrain', 'tm_hm', 'fairy', 'learn_move', 0, 'Ensin Misty Terrain.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fairy.png', false, false),
(3140, 'TM140 Nasty Plot', 'tm_hm', 'dark', 'learn_move', 0, 'Ensin Nasty Plot.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
-- TM141-TM150
(3141, 'TM141 Fire Blast', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Fire Blast.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3142, 'TM142 Hydro Pump', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Hydro Pump.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(3143, 'TM143 Blizzard', 'tm_hm', 'ice', 'learn_move', 0, 'Ensin Blizzard.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
(3144, 'TM144 Fire Pledge', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Fire Pledge.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3145, 'TM145 Water Pledge', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Water Pledge.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(3146, 'TM146 Grass Pledge', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Grass Pledge.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3147, 'TM147 Wild Charge', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Wild Charge.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3148, 'TM148 Sludge Bomb', 'tm_hm', 'poison', 'learn_move', 0, 'Ensin Sludge Bomb.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(3149, 'TM149 Earthquake', 'tm_hm', 'ground', 'learn_move', 0, 'Ensin Earthquake.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(3150, 'TM150 Stone Edge', 'tm_hm', 'rock', 'learn_move', 0, 'Ensin Stone Edge.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-rock.png', false, false),
-- TM151-TM160
(3151, 'TM151 Phantom Force', 'tm_hm', 'ghost', 'learn_move', 0, 'Ensin Phantom Force.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ghost.png', false, false),
(3152, 'TM152 Giga Impact', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Giga Impact.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3153, 'TM153 Blast Burn', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Blast Burn.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3154, 'TM154 Hydro Cannon', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Hydro Cannon.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(3155, 'TM155 Frenzy Plant', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Frenzy Plant.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3156, 'TM156 Outrage', 'tm_hm', 'dragon', 'learn_move', 0, 'Ensin Outrage.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
(3157, 'TM157 Overheat', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Overheat.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3158, 'TM158 Focus Blast', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Focus Blast.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3159, 'TM159 Leaf Storm', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Leaf Storm.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3160, 'TM160 Hurricane', 'tm_hm', 'flying', 'learn_move', 0, 'Ensin Hurricane.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-flying.png', false, false),
-- TM161-TM171
(3161, 'TM161 Trick Room', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Trick Room.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3162, 'TM162 Bug Buzz', 'tm_hm', 'bug', 'learn_move', 0, 'Ensin Bug Buzz.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(3163, 'TM163 Hyper Beam', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Hyper Beam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3164, 'TM164 Brave Bird', 'tm_hm', 'flying', 'learn_move', 0, 'Ensin Brave Bird.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-flying.png', false, false),
(3165, 'TM165 Flare Blitz', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Flare Blitz.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3166, 'TM166 Thunder', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Thunder.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3167, 'TM167 Close Combat', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Close Combat.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3168, 'TM168 Solar Beam', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Solar Beam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3169, 'TM169 Draco Meteor', 'tm_hm', 'dragon', 'learn_move', 0, 'Ensin Draco Meteor.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
(3170, 'TM170 Steel Beam', 'tm_hm', 'steel', 'learn_move', 0, 'Ensin Steel Beam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(3171, 'TM171 Tera Blast', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Tera Blast.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
-- DLC Teal Mask TMs (172-201)
(3172, 'TM172 Roar', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Roar.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3173, 'TM173 Charge', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Charge.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3174, 'TM174 Haze', 'tm_hm', 'ice', 'learn_move', 0, 'Ensin Haze.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
(3175, 'TM175 Toxic', 'tm_hm', 'poison', 'learn_move', 0, 'Ensin Toxic.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(3176, 'TM176 Sand Tomb', 'tm_hm', 'ground', 'learn_move', 0, 'Ensin Sand Tomb.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(3177, 'TM177 Spite', 'tm_hm', 'ghost', 'learn_move', 0, 'Ensin Spite.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ghost.png', false, false),
(3178, 'TM178 Gravity', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Gravity.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3179, 'TM179 Smack Down', 'tm_hm', 'rock', 'learn_move', 0, 'Ensin Smack Down.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-rock.png', false, false),
(3180, 'TM180 Gyro Ball', 'tm_hm', 'steel', 'learn_move', 0, 'Ensin Gyro Ball.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(3181, 'TM181 Knock Off', 'tm_hm', 'dark', 'learn_move', 0, 'Ensin Knock Off.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(3182, 'TM182 Bug Bite', 'tm_hm', 'bug', 'learn_move', 0, 'Ensin Bug Bite.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(3183, 'TM183 Super Fang', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Super Fang.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3184, 'TM184 Vacuum Wave', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Vacuum Wave.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3185, 'TM185 Lunge', 'tm_hm', 'bug', 'learn_move', 0, 'Ensin Lunge.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(3186, 'TM186 High Horsepower', 'tm_hm', 'ground', 'learn_move', 0, 'Ensin High Horsepower.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(3187, 'TM187 Icicle Spear', 'tm_hm', 'ice', 'learn_move', 0, 'Ensin Icicle Spear.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
(3188, 'TM188 Scald', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Scald.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(3189, 'TM189 Heat Crash', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Heat Crash.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3190, 'TM190 Solar Blade', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Solar Blade.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3191, 'TM191 Uproar', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Uproar.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3192, 'TM192 Focus Punch', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Focus Punch.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3193, 'TM193 Weather Ball', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Weather Ball.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3194, 'TM194 Grassy Glide', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Grassy Glide.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3195, 'TM195 Burning Jealousy', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Burning Jealousy.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3196, 'TM196 Flip Turn', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Flip Turn.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(3197, 'TM197 Dual Wingbeat', 'tm_hm', 'flying', 'learn_move', 0, 'Ensin Dual Wingbeat.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-flying.png', false, false),
(3198, 'TM198 Poltergeist', 'tm_hm', 'ghost', 'learn_move', 0, 'Ensin Poltergeist.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ghost.png', false, false),
(3199, 'TM199 Lash Out', 'tm_hm', 'dark', 'learn_move', 0, 'Ensin Lash Out.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(3200, 'TM200 Scale Shot', 'tm_hm', 'dragon', 'learn_move', 0, 'Ensin Scale Shot.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
(3201, 'TM201 Misty Explosion', 'tm_hm', 'fairy', 'learn_move', 0, 'Ensin Misty Explosion.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fairy.png', false, false),
-- DLC Indigo Disk TMs (202-229)
(3202, 'TM202 Pain Split', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Pain Split.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3203, 'TM203 Psych Up', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Psych Up.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3204, 'TM204 Double-Edge', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Double-Edge.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3205, 'TM205 Endeavor', 'tm_hm', 'normal', 'learn_move', 0, 'Ensin Endeavor.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png', false, false),
(3206, 'TM206 Petal Blizzard', 'tm_hm', 'grass', 'learn_move', 0, 'Ensin Petal Blizzard.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-grass.png', false, false),
(3207, 'TM207 Temper Flare', 'tm_hm', 'fire', 'learn_move', 0, 'Ensin Temper Flare.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fire.png', false, false),
(3208, 'TM208 Whirlpool', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Whirlpool.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(3209, 'TM209 Muddy Water', 'tm_hm', 'water', 'learn_move', 0, 'Ensin Muddy Water.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-water.png', false, false),
(3210, 'TM210 Supercell Slam', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Supercell Slam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3211, 'TM211 Electroweb', 'tm_hm', 'electric', 'learn_move', 0, 'Ensin Electroweb.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-electric.png', false, false),
(3212, 'TM212 Triple Axel', 'tm_hm', 'ice', 'learn_move', 0, 'Ensin Triple Axel.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ice.png', false, false),
(3213, 'TM213 Coaching', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Coaching.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false),
(3214, 'TM214 Sludge Wave', 'tm_hm', 'poison', 'learn_move', 0, 'Ensin Sludge Wave.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-poison.png', false, false),
(3215, 'TM215 Scorching Sands', 'tm_hm', 'ground', 'learn_move', 0, 'Ensin Scorching Sands.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ground.png', false, false),
(3216, 'TM216 Feather Dance', 'tm_hm', 'flying', 'learn_move', 0, 'Ensin Feather Dance.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-flying.png', false, false),
(3217, 'TM217 Future Sight', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Future Sight.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3218, 'TM218 Expanding Force', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Expanding Force.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3219, 'TM219 Skitter Smack', 'tm_hm', 'bug', 'learn_move', 0, 'Ensin Skitter Smack.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-bug.png', false, false),
(3220, 'TM220 Meteor Beam', 'tm_hm', 'rock', 'learn_move', 0, 'Ensin Meteor Beam.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-rock.png', false, false),
(3221, 'TM221 Throat Chop', 'tm_hm', 'dark', 'learn_move', 0, 'Ensin Throat Chop.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dark.png', false, false),
(3222, 'TM222 Breaking Swipe', 'tm_hm', 'dragon', 'learn_move', 0, 'Ensin Breaking Swipe.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
(3223, 'TM223 Metal Sound', 'tm_hm', 'steel', 'learn_move', 0, 'Ensin Metal Sound.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(3224, 'TM224 Curse', 'tm_hm', 'ghost', 'learn_move', 0, 'Ensin Curse.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-ghost.png', false, false),
(3225, 'TM225 Hard Press', 'tm_hm', 'steel', 'learn_move', 0, 'Ensin Hard Press.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-steel.png', false, false),
(3226, 'TM226 Dragon Cheer', 'tm_hm', 'dragon', 'learn_move', 0, 'Ensin Dragon Cheer.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-dragon.png', false, false),
(3227, 'TM227 Alluring Voice', 'tm_hm', 'fairy', 'learn_move', 0, 'Ensin Alluring Voice.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fairy.png', false, false),
(3228, 'TM228 Psychic Noise', 'tm_hm', 'psychic', 'learn_move', 0, 'Ensin Psychic Noise.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-psychic.png', false, false),
(3229, 'TM229 Upper Hand', 'tm_hm', 'fighting', 'learn_move', 0, 'Ensin Upper Hand.', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-fighting.png', false, false)

ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    effect = EXCLUDED.effect,
    effect_value = EXCLUDED.effect_value,
    description = EXCLUDED.description,
    price = EXCLUDED.price,
    sprite_url = EXCLUDED.sprite_url,
    holdable = EXCLUDED.holdable,
    usable_in_battle = EXCLUDED.usable_in_battle;

SELECT 'TMs total: ' || count(*)::text FROM items WHERE category = 'tm_hm';
