-- Gen 9 Missing Pokemon (auto-generated)
-- IDs 1001-1025 from PokeAPI
INSERT INTO pokemon (id, name, types, hp, attack, defense, sp_atk, sp_def, speed, sprite_official, sprite_home, variant, base_pokemon_id)
VALUES
(1001, 'wo-chien', '{dark,grass}', 85, 85, 100, 95, 135, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1001.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1001.png', 'normal', NULL),
(1002, 'chien-pao', '{dark,ice}', 80, 120, 80, 90, 65, 135, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1002.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1002.png', 'normal', NULL),
(1003, 'ting-lu', '{dark,ground}', 155, 110, 125, 55, 80, 45, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1003.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1003.png', 'normal', NULL),
(1004, 'chi-yu', '{dark,fire}', 55, 80, 80, 135, 120, 100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1004.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1004.png', 'normal', NULL),
(1005, 'roaring-moon', '{dragon,dark}', 105, 139, 71, 55, 101, 119, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1005.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1005.png', 'normal', NULL),
(1006, 'iron-valiant', '{fairy,fighting}', 74, 130, 90, 120, 60, 116, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1006.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1006.png', 'normal', NULL),
(1007, 'koraidon', '{fighting,dragon}', 100, 135, 115, 85, 100, 135, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1007.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1007.png', 'normal', NULL),
(1008, 'miraidon', '{electric,dragon}', 100, 85, 100, 135, 115, 135, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1008.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1008.png', 'normal', NULL),
(1009, 'walking-wake', '{water,dragon}', 99, 83, 91, 125, 83, 109, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1009.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1009.png', 'normal', NULL),
(1010, 'iron-leaves', '{grass,psychic}', 90, 130, 88, 70, 108, 104, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1010.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1010.png', 'normal', NULL),
(1011, 'dipplin', '{grass,dragon}', 80, 80, 110, 95, 80, 40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1011.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1011.png', 'normal', NULL),
(1012, 'poltchageist', '{grass,ghost}', 40, 45, 45, 74, 54, 50, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1012.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1012.png', 'normal', NULL),
(1013, 'sinistcha', '{grass,ghost}', 71, 60, 106, 121, 80, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1013.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1013.png', 'normal', NULL),
(1014, 'okidogi', '{poison,fighting}', 88, 128, 115, 58, 86, 80, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1014.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1014.png', 'normal', NULL),
(1015, 'munkidori', '{poison,psychic}', 88, 75, 66, 130, 90, 106, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1015.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1015.png', 'normal', NULL),
(1016, 'fezandipiti', '{poison,fairy}', 88, 91, 82, 70, 125, 99, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1016.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1016.png', 'normal', NULL),
(1017, 'ogerpon', '{grass}', 80, 120, 84, 60, 96, 110, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1017.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1017.png', 'normal', NULL),
(1018, 'archaludon', '{steel,dragon}', 90, 105, 130, 125, 65, 85, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1018.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1018.png', 'normal', NULL),
(1019, 'hydrapple', '{grass,dragon}', 106, 80, 110, 120, 80, 44, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1019.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1019.png', 'normal', NULL),
(1020, 'gouging-fire', '{fire,dragon}', 105, 115, 121, 65, 93, 91, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1020.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1020.png', 'normal', NULL),
(1021, 'raging-bolt', '{electric,dragon}', 125, 73, 91, 137, 89, 75, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1021.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1021.png', 'normal', NULL),
(1022, 'iron-boulder', '{rock,psychic}', 90, 120, 80, 68, 108, 124, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1022.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1022.png', 'normal', NULL),
(1023, 'iron-crown', '{steel,psychic}', 90, 72, 100, 122, 108, 98, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1023.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1023.png', 'normal', NULL),
(1024, 'terapagos', '{normal}', 90, 65, 85, 65, 85, 60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1024.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1024.png', 'normal', NULL),
(1025, 'pecharunt', '{poison,ghost}', 88, 88, 160, 88, 88, 88, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1025.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1025.png', 'normal', NULL)
ON CONFLICT (id) DO NOTHING;
