-- Professor Carvalho quest tables
-- Run this SQL in Supabase SQL Editor

create table if not exists city_professor_quests (
    id bigint generated by default as identity primary key,
    npc_id uuid not null references city_npcs(id) on delete cascade,
    order_index integer not null default 0,
    quest_type text not null,
    title text not null,
    description text,
    target_count integer default 1,
    target_biome text,
    target_pokemon_id bigint,
    target_pokemon_name text,
    pvp_required boolean default false,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists city_professor_quest_rewards (
    id bigint generated by default as identity primary key,
    quest_id bigint not null references city_professor_quests(id) on delete cascade,
    reward_type text not null,
    amount integer default 0,
    pokemon_id bigint,
    item_id bigint,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists player_professor_quests (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    character_id uuid not null,
    npc_id uuid not null references city_npcs(id) on delete cascade,
    quest_id bigint not null references city_professor_quests(id) on delete cascade,
    status text not null default 'locked',
    progress integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(user_id, character_id, quest_id)
);
